import type { NextPage } from "next";
import { Button } from "@mui/material";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const Entry: NextPage = () => {
  const router = useRouter();
  const [web3WalletReadyState, setWeb3WalletReadyState] = useState(false);
  const [entranceType, setEntranceType] = useState<"default" | "web3" | "web2">(
    "default"
  );

  useEffect(() => {
    setWeb3WalletReadyState(
      typeof (window as any).ethereum == "object" &&
        typeof (window as any).ethereum.chainId == "string"
    );
  }, []);

  const getEntrancePanel = (entranceType: "default" | "web3" | "web2") => {
    // state: web3WalletReadyState dependent on Entry components.
    // state function: setEntranceType dependent on Entry components.
    // Warning: This function is "strongly dependent on the 'parent' component"
    //          it should not be used on other components!

    switch (entranceType) {
      case "web2":
        return <>web2</>;
      case "web3":
        return <>web3</>;
      default:
        return (
          <>
            <button
              className="border border-gray-500 bg-gray-900 p-3 hover:bg-gray-500"
              onClick={() => {
                router.back();
              }}
            >
              {"<< BACK"}
            </button>
            <div className="border border-gray-500 p-10 bg-gray-800 max-w-4xl flex flex-col md:flex-row mt-4">
              {/* CARD LEFT */}
              <div className=" h-40 w-40 md border border-gray-700 flex-none">
                {/* TODO: change entry img */}
                <Image
                  src="/entry-img.png"
                  alt="Entry img"
                  width={160}
                  height={160}
                />
              </div>
              {/* CARD RIGHT */}
              <div className="ml-0 md:ml-8 mt-12 md:mt-0 flex flex-col justify-between md:basis-3/4">
                {/* CARD RIGHT TOP */}
                <div>
                  <h2 className=" text-2xl">Access via Web3</h2>
                  <p className=" font-thin">
                    You need to access the User Center via the Ethernet wallet
                    Metamask
                  </p>
                </div>
                {/* CARD LEFT BOTTOM */}
                <div className="flex flex-row justify-end mt-6 md:mt-0">
                  {web3WalletReadyState ? (
                    <button
                      className=" bg-gray-500 p-3 hover:bg-slate-400 font-thin"
                      onClick={() => {
                        setEntranceType("web3");
                      }}
                    >
                      Start & Access
                    </button>
                  ) : (
                    <div className=" bg-gray-700 p-3 text-gray-500">
                      Please install Web3 wallet
                    </div>
                  )}
                </div>
              </div>
            </div>

            <div className="border border-gray-500 p-10 bg-gray-800 max-w-4xl flex flex-col md:flex-row mt-4">
              {/* CARD LEFT */}
              <div className=" h-40 w-40 md border border-gray-700 flex-none">
                {/* TODO: change entry img */}
                <Image
                  src="/entry-img.png"
                  alt="Entry img"
                  width={160}
                  height={160}
                />
              </div>
              {/* CARD RIGHT */}
              <div className="ml-0 md:ml-8 mt-12 md:mt-0 flex flex-col justify-between md:basis-3/4">
                {/* CARD RIGHT TOP */}
                <div>
                  <h2 className=" text-2xl">Access via Web2</h2>
                  <p className=" font-thin">
                    You can use our provided (or third-party provided) Web2
                    proxy facility to access the User Center by entering a
                    traditional TOKEN authentication method to access the User
                    Center
                  </p>
                </div>
                {/* CARD LEFT BOTTOM */}
                <div className="flex flex-row justify-end mt-6 md:mt-0">
                  <button
                    className=" bg-gray-500 p-3 hover:bg-slate-400 font-thin"
                    onClick={() => {
                      setEntranceType("web2");
                    }}
                  >
                    Access to the User Center via Web2 proxy
                  </button>
                </div>
              </div>
            </div>
          </>
        );
    }
  };

  return (
    <>
      <Head>
        <title>User Center Entrance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <_JSXStyle id="entry">{`body { background: "rgb(17 24 39)"; }`}</_JSXStyle> */}
      <div className=" sm:h-screen bg-gray-900 text-white flex flex-col justify-start md:justify-center items-center p-4">
        <div className="max-w-4xl py-20 ">
          <> {getEntrancePanel(entranceType)} </>
        </div>
      </div>
    </>
  );
};

export default Entry;
